project:
  type: website

website:
  title: "Blog de Inmaculada Osuna Muñoz"
  navbar:
    right:
      - about.qmd
      - cv.qmd
      - icon: linkedin
        href: www.linkedin.com/in/inmaculada-osuna-muñoz-842664364
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
